convert store to es6 class to make typescript compile the declaration file correctly.
Without this changes, typescript would return error TS9005 "Declaration emit for this file requires using private name " "An explicit type annotation may unblock declaration".